---
apiVersion: v1
kind: Service
metadata:
  name: ray-serve
spec:
  type: ClusterIP
  selector:
    ray.io/node-type: head
  ports:
    - name: serve
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ray-dashboard
spec:
  type: NodePort
  selector:
    ray.io/node-type: head
  ports:
    - name: dashboard
      port: 8265
      targetPort: 8265
      nodePort: 31100
